name: security-api

on:
  push:
    branches:
      - develop

env:
  DEFECTDOJO_URL: https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app
  DEFECTDOJO_API_VERSION: v2

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare workspace
        run: |
          mkdir -p target
          # Verifica se existem arquivos de filtro
          if [ ! -f spotbugs-security-exclude.xml ]; then
            echo "<FindBugsFilter></FindBugsFilter>" > spotbugs-security-exclude.xml
          fi
          if [ ! -f spotbugs-security-include.xml ]; then
            echo "<FindBugsFilter></FindBugsFilter>" > spotbugs-security-include.xml
          fi

      - name: Run SpotBugs with explicit settings
        run: |
          mvn spotbugs:spotbugs \
            -Dspotbugs.failOnError=false \
            -Dspotbugs.xmlOutput=true \
            -Dspotbugs.outputFile=${{ env.SPOTBUGS_REPORT_PATH }} \
            -Dspotbugs.effort=Max \
            -Dspotbugs.reportLevel=low \
            -Dspotbugs.excludeFilterFile=spotbugs-security-exclude.xml \
            -Dspotbugs.includeFilterFile=spotbugs-security-include.xml \
            -Dproject.build.outputDirectory=target/classes \
            -Dproject.build.testOutputDirectory=target/test-classes

      - name: Verify report generation
        run: |
          echo "Conteúdo do diretório target:"
          ls -la target/
          echo "Verificando relatório em ${{ env.SPOTBUGS_REPORT_PATH }}"
          if [ -f "${{ env.SPOTBUGS_REPORT_PATH }}" ]; then
            echo "Relatório encontrado!"
            cat ${{ env.SPOTBUGS_REPORT_PATH }} | head -n 20
          else
            echo "##[error]Relatório não encontrado!"
            find . -name "*.xml" | grep -i "bug" || echo "Nenhum arquivo XML encontrado"
          fi


      - name: Full recursive listing of target directory
        run: |
          echo "###########################################"
          echo "## LISTAGEM COMPLETA DO DIRETÓRIO TARGET ##"
          echo "###########################################"
          echo ""
          echo "Estrutura hierárquica completa:"
          find target/ -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
          
          echo ""
          echo "-------------------------------------------"
          echo "Conteúdo detalhado:"
          ls -Rla target/
          
          echo ""
          echo "-------------------------------------------"
          echo "Arquivos XML encontrados:"
          find target/ -name "*.xml" -exec ls -la {} \;
          
          echo ""
          echo "-------------------------------------------"
          echo "Arquivos relacionados a SpotBugs:"
          find target/ -name "*spotbugs*" -o -name "*findbugs*" -exec ls -la {} \; || echo "Nenhum arquivo encontrado"
          
          echo ""
          echo "-------------------------------------------"
          echo "Espaço utilizado:"
          du -sh target/*
          
          echo ""
          echo "-------------------------------------------"
          echo "Arquivos mais recentes (últimos 5 modificados):"
          find target/ -type f -printf "%T+ %p\n" | sort -r | head -n 5   

      - name: Process SpotBugs findings
        if: success() || failure()
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: ${{ env.SPOTBUGS_REPORT_PATH }}
          name: 'SpotBugs Report'
          continue-on-warning: true

      - name: Upload to DefectDojo
        if: always()
        run: |
          if [ -f "${{ env.SPOTBUGS_REPORT_PATH }}" ]; then
            echo "Enviando relatório para DefectDojo..."
            curl -v -X POST "${{ env.DEFECTDOJO_URL }}/api/${{ env.DEFECTDOJO_API_VERSION }}/import-scan/" \
              -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
              -F "scan_type=SpotBugs Scan" \
              -F "file=@${{ env.SPOTBUGS_REPORT_PATH }}" \
              -F "product_name=api-clone-ifood" \
              -F "engagement_name=Automated-Scan-$(date +%Y%m%d)" \
              -F "auto_create_context=true"
          else
            echo "##[warning]Relatório SpotBugs não encontrado para upload"
          fi

         
      # - name: Enviar relatório para API
      #   run: |
      #     curl -v -X POST "https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app/api/v2/import-scan/" \
      #       -H "Authorization: Token 6e482a959eefdd5e09dfe983f010a443c2616a74" \
      #       -F "scan_type=SpotBugs Scan" \
      #       -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target" \
      #       -F "product_name=api-clone-ifood" \
      #       -F "engagement_name=Teste-Manual-$(date +%Y%m%d)" \
      #       -F "auto_create_context=true"

      # SCA - OWASP Dependency-Check
      # - name: Run OWASP Dependency-Check
      #   run: |
      #     mvn dependency-check:check -Dformat=XML
      #     curl -X POST "https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app/api/v2/import-scan/" \
      #       -H "Authorization: Token 6e482a959eefdd5e09dfe983f010a443c2616a74" \
      #       -F "scan_type=Dependency Check Scan" \
      #       -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target/dependency-check-report.xml" \
      #       -F "engagement=1"

      - name: Notify telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            O evento ${{ github.event_name }} realizou a pipeline ${{ github.workflow }}.
            *Repositorio*: [${{ github.repository }}](${{ github.repo.url }})  
            Quem realizou o commit: ${{ github.event.commits[0].author.name }}
            Mensagem do commit: ${{ github.event.commits[0].message }}.
            *Relatórios de segurança enviados para o DefectDojo*
