name: security-api

on:
  push:
    branches:
      - develop

env:
  DEFECTDOJO_URL: https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app
  DEFECTDOJO_API_VERSION: v2

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run SpotBugs with Maven
        run: |
          # Configuração explícita do output directory
          mvn spotbugs:spotbugs \
            -Dspotbugs.failOnError=false \
            -Dspotbugs.xmlOutput=true \
            -Dspotbugs.outputDirectory=target/spotbugs \
            -Dspotbugs.reportLevel=low \
            -Dspotbugs.effort=Max \
            -Dspotbugs.pluginVersion=${{ env.SPOTBUGS_VERSION }} \
            -Dspotbugs.includeTests=true \
            -Dspotbugs.excludeFilterFile=.spotbugs-exclude.xml \
            -X

      - name: Verify SpotBugs report location
        run: |
          echo "Conteúdo do diretório target/spotbugs:"
          ls -la ${{ github.workspace }}/target/spotbugs || echo "Diretório não encontrado"
          
          echo "Buscando relatório em todo o workspace:"
          find ${{ github.workspace }} -name "*spotbugs*" -o -name "*findbugs*"

      - name: Process SpotBugs report
        if: success() || failure()  # Executa mesmo se o passo anterior falhar
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
          name: 'SpotBugs Report'

      - name: Upload SpotBugs report to DefectDojo
        run: |
          # Tenta encontrar o relatório em vários locais possíveis
          REPORT_PATH=$(find ${{ github.workspace }} -name "spotbugsXml.xml" -o -name "findbugsXml.xml" | head -1)
          
          if [ -f "$REPORT_PATH" ]; then
            echo "Enviando relatório encontrado em: $REPORT_PATH"
            curl -v -X POST "${{ env.DEFECTDOJO_URL }}/api/${{ env.DEFECTDOJO_API_VERSION }}/import-scan/" \
              -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
              -F "scan_type=SpotBugs Scan" \
              -F "file=@$REPORT_PATH" \
              -F "product_name=api-clone-ifood" \
              -F "engagement_name=Automated-Scan-$(date +%Y%m%d)" \
              -F "auto_create_context=true"
          else
            echo "##[warning]Relatório SpotBugs não encontrado nos locais esperados"
            echo "##[warning]Os locais verificados foram:"
            find ${{ github.workspace }} -name "*spotbugs*" -o -name "*findbugs*"
            # Não falha o job intencionalmente
          fi

         
      # - name: Enviar relatório para API
      #   run: |
      #     curl -v -X POST "https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app/api/v2/import-scan/" \
      #       -H "Authorization: Token 6e482a959eefdd5e09dfe983f010a443c2616a74" \
      #       -F "scan_type=SpotBugs Scan" \
      #       -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target" \
      #       -F "product_name=api-clone-ifood" \
      #       -F "engagement_name=Teste-Manual-$(date +%Y%m%d)" \
      #       -F "auto_create_context=true"

      # SCA - OWASP Dependency-Check
      # - name: Run OWASP Dependency-Check
      #   run: |
      #     mvn dependency-check:check -Dformat=XML
      #     curl -X POST "https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app/api/v2/import-scan/" \
      #       -H "Authorization: Token 6e482a959eefdd5e09dfe983f010a443c2616a74" \
      #       -F "scan_type=Dependency Check Scan" \
      #       -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target/dependency-check-report.xml" \
      #       -F "engagement=1"

      - name: Notify telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            O evento ${{ github.event_name }} realizou a pipeline ${{ github.workflow }}.
            *Repositorio*: [${{ github.repository }}](${{ github.repo.url }})  
            Quem realizou o commit: ${{ github.event.commits[0].author.name }}
            Mensagem do commit: ${{ github.event.commits[0].message }}.
            *Relatórios de segurança enviados para o DefectDojo*
