name: security-api

on:
  push:
    branches:
      - develop

env:
  DEFECTDOJO_URL: https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app
  DEFECTDOJO_API_VERSION: v2
  DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_API_KEY }} 
  DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # SAST - FindSecBugs
      - name: Run FindSecBugs with Maven
        run: |
          mvn spotbugs:spotbugs -Dspotbugs.failOnError=false
          if [ -f target/spotbugsXml.xml ]; then
            curl -v -X POST "https://50cf-2804-29b8-5004-8382-b30e-9893-1b68-4d59.ngrok-free.app/api/v2/import-scan/" \
              -H "Authorization: Token ${{ env.DEFECTDOJO_TOKEN }}" \
              -F "scan_type=SpotBugs Scan" \
              -F "file=@target/spotbugsXml.xml" \
              -F "product_name=api-clone-ifood" \
              -F "engagement_name=Teste-Manual-$(date +%Y%m%d)" \
              -F "auto_create_context=true"
          fi

      # SCA - OWASP Dependency-Check
      - name: Run OWASP Dependency-Check          
        run: |
          mvn dependency-check:check -Dformat=XML
          curl -v -X POST "${{ env.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ env.DEFECTDOJO_TOKEN }}" \
            -F "scan_type=Dependency Check Scan" \
            -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target/dependency-check-report.xml" \
            -F "engagement=${{ env.DEFECTDOJO_ENGAGEMENT_ID }}"

        

      - name: Notify telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            O evento ${{ github.event_name }} realizou a pipeline ${{ github.workflow }}.
            *Repositorio*: [${{ github.repository }}](${{ github.repo.url }})  
            Quem realizou o commit: ${{ github.event.commits[0].author.name }}
            Mensagem do commit: ${{ github.event.commits[0].message }}.
            *Relatórios de segurança enviados para o DefectDojo*
