name: security-api

on:
  push:
    branches:
      - develop

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Ddependency-check.skip=true -Dsonar.projectKey=Arthurlevicoelho_api-clone-ifood_f8ea70ca-3c4d-4893-98ca-1b33ecb5eb3f -Dsonar.projectName='api-clone-ifood' -DskipTests=true

      - name: Install sonar-report
        run: npm install -g sonar-report

      - name: Generate SonarQube report
        run: |
          sonar-report --sonarurl=${{ secrets.SONAR_HOST_URL }} --sonartoken=${{ secrets.SONAR_TOKEN }} --sonarcomponent=api-clone-ifood --project=ifood-backend --branch=main --release=0.0.1-SNAPSHOT --save-report-json=/home/runner/work/api-clone-ifood/api-clone-ifood/target/sonar-report.json --no-security-hotspot

      - name: Import SonarQube to DefectDojo
        run: |
          curl -k -X POST "${{ secrets.DEFECT_DOJO_URL }}" \
            -H "Authorization: ${{ secrets.DEFECT_DOJO_API_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=SonarQube Scan" \
            -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target/sonar-report.json" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}"
    
         
      - name: Run OWASP Dependency-Check
        run: |
         mvn dependency-check:check -Dformat=XML
          

      - name: Import to DefectDojo
        run: |
          curl -k -X POST "${{ secrets.DEFECT_DOJO_URL }}" \
           -H "Authorization: ${{ secrets.DEFECT_DOJO_API_KEY }}" \
           -F "scan_type=Dependency Check Scan" \
           -F "file=@/home/runner/work/api-clone-ifood/api-clone-ifood/target/dependency-check-report.xml" \
           -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}"

      - name: Notify telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            O evento ${{ github.event_name }} realizou a pipeline ${{ github.workflow }}.
            *Repositorio*: [${{ github.repository }}](${{ github.repo.url }})  
            Quem realizou o commit: ${{ github.event.commits[0].author.name }}
            Mensagem do commit: ${{ github.event.commits[0].message }}.
            * Relatórios de segurança enviados para o DefectDojo *
